CXX = g++ -std=c++11
OBJ = main.o DNS.o cache.o blacklist.o log.o

all: dnsrelay

dnsrelay: $(OBJ)
	$(CXX) -o $(OBJ)

main.o: main.cpp main.h
	$(CXX) -c main.cpp

DNS.o: DNS.cpp DNS.h
	$(CXX) -c DNS.cpp

cache.o: cache.cpp cache.h
	$(CXX) -c cache.cpp

blacklist.o: blacklist.cpp blacklist.h
	$(CXX) -c blacklist.cpp

log.o: log.cpp log.h
	$(CXX) -c log.cpp
